services:
  - type: web
    name: smart-study-notes-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: HF_TOKEN
        sync: false
